import type { Clothing, Outfit, User } from '@/types'

export const mockUser: User = {
  id: 'user_1',
  email: 'test@example.com',
  name: 'Sarah Johnson',
  avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Sarah',
  createdAt: new Date('2024-01-01'),
}

export const mockClothing: Clothing[] = [
  {
    id: 'clothing_1',
    name: 'White Casual T-Shirt',
    category: 'top',
    color: 'white',
    description: 'Perfect for casual everyday wear',
    tags: ['casual', 'cotton', 'basic'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'clothing_2',
    name: 'Blue Denim Jeans',
    category: 'bottom',
    color: 'blue',
    description: 'Classic fit denim',
    tags: ['casual', 'denim', 'versatile'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'clothing_3',
    name: 'Black Leather Jacket',
    category: 'outerwear',
    color: 'black',
    description: 'Timeless leather jacket',
    tags: ['edgy', 'formal', 'versatile'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'clothing_4',
    name: 'Black Skinny Jeans',
    category: 'bottom',
    color: 'black',
    description: 'Slim fit, perfect for dressy occasions',
    tags: ['formal', 'dressy', 'black'],
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'clothing_5',
    name: 'White Button-Up Blouse',
    category: 'top',
    color: 'white',
    description: 'Professional and elegant',
    tags: ['professional', 'formal', 'work'],
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'clothing_6',
    name: 'Beige Cardigan',
    category: 'outerwear',
    color: 'beige',
    description: 'Cozy and versatile cardigan',
    tags: ['cozy', 'layering', 'neutral'],
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 'clothing_7',
    name: 'Sneakers - White',
    category: 'footwear',
    color: 'white',
    description: 'Comfortable white sneakers',
    tags: ['casual', 'comfortable', 'sneakers'],
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'clothing_8',
    name: 'Black Heels',
    category: 'footwear',
    color: 'black',
    description: 'Elegant black heels for formal events',
    tags: ['formal', 'dressy', 'heels'],
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'clothing_9',
    name: 'Gold Necklace',
    category: 'accessory',
    color: 'gold',
    description: 'Delicate gold pendant necklace',
    tags: ['accessory', 'jewelry', 'elegant'],
    createdAt: new Date('2024-02-05'),
  },
  {
    id: 'clothing_10',
    name: 'Striped Sweater',
    category: 'top',
    color: 'blue',
    description: 'Navy and white striped sweater',
    tags: ['casual', 'cozy', 'stripes'],
    createdAt: new Date('2024-02-05'),
  },
]

export const mockOutfits: Outfit[] = [
  {
    id: 'outfit_1',
    name: 'Casual Weekend',
    description: 'Perfect for a relaxed weekend brunch',
    items: [mockClothing[0]!, mockClothing[1]!, mockClothing[6]!],
    occasions: ['casual', 'weekend', 'brunch'],
    weather: 'mild',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'outfit_2',
    name: 'Business Casual',
    description: 'Office-appropriate outfit',
    items: [mockClothing[4]!, mockClothing[3]!, mockClothing[7]!, mockClothing[8]!],
    occasions: ['work', 'professional', 'meeting'],
    weather: 'mild',
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-12'),
  },
  {
    id: 'outfit_3',
    name: 'Evening Chic',
    description: 'Sophisticated look for dinner date',
    items: [mockClothing[4]!, mockClothing[3]!, mockClothing[2]!, mockClothing[7]!],
    occasions: ['date', 'dinner', 'evening'],
    weather: 'mild',
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-02-14'),
  },
  {
    id: 'outfit_4',
    name: 'Cozy Autumn',
    description: 'Comfortable layered look for cooler weather',
    items: [mockClothing[9]!, mockClothing[1]!, mockClothing[5]!, mockClothing[6]!],
    occasions: ['casual', 'comfortable'],
    weather: 'cold',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
]
